
<?php $__env->startSection('title', 'License Agreement for SaaS'); ?>
<?php $__env->startSection('body-class', 'white-bg'); ?>
<?php $__env->startSection('content'); ?>
<div class="main-section">
    <?php echo $__env->make("includes.header", \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
</div>
<div class="container footer_page">
    <div class="legal-wrapper">
        <h1 class="legal-title">License Agreement for SaaS<br><span class="legal-subtitle">Terms&nbsp;&amp; Conditions</span></h1>
        <div class="legal-date">Last update: 28/04/2022</div>
        <div class="legal-rich-text w-richtext">
            <h2>1. Definitions</h2>
            <p>“DataTile Platform” means the software (including firmware, middleware,applications, APIs, web widgets, code and related algorithms, models and methodologies, files, documentation) that performs the calculations for data analysis, reporting and representation of results. DataTile Ltd. owns all Intellectual Property Rights on the DataTile Platform. </p>
            <p>“Account” shall mean registered private access to DataTile Platform with assigned username and password;</p>
            <p>“Agreement” means this license agreement together with the Order confirmation executed by and between the Parties;</p>
            <p>“Business Day” means Monday to Friday, with the exception of any day that banks in Cyprus are closed for regular business;</p>
            <p>“DataTile Improvement” means any improvement, modification, translation, update,upgrade, new version of DataTile Platform, as well as enhancement or other derivative work;</p>
            <p>“Delivery” shall have the meaning set forth in Subsection 2.2;</p>
            <p>“Documentation” means all standard functional and technical specifications,technical requirements, user manuals, diagrams, file descriptions, and similar written materials relating to the DataTile Platform;</p>
            <p>“Effective Date” shall mean the date on which this Agreement is executed by Licensor and Licensee;</p>
            <p>"End User" means any person of the Licensee or their clients who maybe entitled to have access to the DataTile Platform via Accounts, created by the Licensee;</p>
            <p>“Error” means any failure of the DataTile Platform to function properly or conform in all material respects to its Documentation;</p>
            <p>“Force Majeure Event” means any circumstances beyond the reasonable control of a Party (and unknown to such Party at the date of this Agreement) including but not limited to acts of God, fire, explosion, adverse weather, flood, terrorism,civil commotion, war and riots; For avoidance of doubt, any failure of the Licensor’s subcontractors shall not be considered as a Force Majeure Event;</p>
            <p>“Intellectual Property Rights” means all DataTile proprietary rights, licenses, title and interest in any intellectual property rights including (but not limited to)industrial property rights, trademarks (registered or unregistered), rights in invention, service marks, patents, copyrights, design rights, database rights registered, designs and know-how, algorithms, APIs, databases, diagrams,formulae, inventions (whether or not patentable), configurations and architectures, processes and workflows, proprietary information, protocols,specifications, software code programs languages and codes rights, (in any form, including source code, and executable or object code), subroutines,techniques, user interfaces, URLs, (whether or not embodied in any tangible form and including all tangible embodiments of the foregoing, such as instruction manuals, prototypes, notebooks, samples, studies and summaries) subsisting in certain or all countries throughout the World;</p>
            <p>"First License Year" means the twelve-month period beginning on the Effective date and running accordingly;</p>
            <p>"License Year" means the First License Year or any Subsequent LicenseYear;</p>
            <p>"Subsequent License Year" means each twelve-month period after the First License Year, with each subsequent License Year beginning on the Effective Date of the then-current year and running accordingly.</p>
            <p>“Licensee Data” means (i) any data, uploaded and used together with the DataTile Platform by Licensee or End Users, (ii) aggregated information, usage and traffic data, names and addresses, passwords, registration information, and cookie information related to &nbsp;theDataTile Platform; (iii) any reports and data calculations, produced by the DataTile Platform;</p>
            <p>“Term of Agreement” shall have the meaning set forth in Subsection&nbsp;7.1;</p>
            <p>“Term of License” shall have the meaning set forth in Subsection&nbsp;2.3.</p>
            <h2>2. License</h2>
            <p><strong>2.1. Grant of License. </strong>Provided the Licensee fully complies with its obligations under this Agreement, the Licensor shall grant to the Licensee a non-exclusive,non-transferable, time-limited license pursuant to which the Licensee shall be allowed and use<sup>[1]</sup> one production instance of the DataTile Platform preinstalled on the servers of the Licensor or in the cloud platforms in accordance with the capacities described in the Order confirmation during the Term of License.</p>
            <p>The Licensee is entitled to provide access to the DataTile Platform to the End Users via created Accounts.</p>
            <p><strong>2.2. Delivery. </strong>Within 2 (two) days upon receipt of the full payment based on the executed Order confirmation the Licensor shall deliver to the Licensee &nbsp;the information and unique registration link,which will allow the Licensee to create Account and to access the preinstalled production instance of the DataTile Platform (the “Delivery Date”).</p>
            <p><strong>2.3. The Term of License. </strong>The Term of License begins on the Effective date and shall terminate at the end of First License Year. The Term of License can be extended by mutual agreement for Subsequent License Year period at end of each License Year provided that Licensee duly pays all applicable License Fees under Section 3.</p>
            <p><strong>2.4. License Restrictions.</strong> The Licensee shall not be entitled to make any changes to the DataTile Platform, including but not limited to reverse engineer, decompile, or disassemble the DataTile Platform.</p>
            <p><strong>2.5. Form of use. </strong>The Licensee agrees to use the DataTile Platform only according to the Documentation and to the terms and conditions of this Agreement. Those uses existing as of the day this Agreement is executed are deemed acceptable and representative of the types of uses the Licensor has approved and such uses together with any other uses approved by the Licensor. Notwithstanding the foregoing the Licensor may amend the Documentation based on the updates made to the DataTile Platform which will be binding for the Licensee immediately upon publishing of such Documentation on the web-site of the Licensor or delivery of the Documentation to the Licensee’s email address.</p>
            <p><strong>2.6. Improvements. </strong>The Licensee acknowledges that the Licensor is under no obligation to create any Improvements to the DataTile Platform. If the Licensor independently creates or develops any Improvements to the DataTile Platformduring the Term of License, Licensor shall license or offer the Licensee access to such DataTile Improvements at such time as those Improvements were created or developed, but in all cases, free of any fees or charges, shall deliver any such Improvements to the Licensee. For the avoidance of doubt, such DataTile Improvements shall be deemed as the DataTile Platform for the purposes of this Agreement and licensed to the Licensee pursuant to the License granted in Subsection&nbsp;2.1.</p>
            <p><strong>2.7. Technical Support</strong>. During the Term of License, the Licensor shall continue to provide or cause to be provided Error rectification with respect to the DataTile Platform (“Technical support”). In the event the Licensee discovers Errors in the DataTile Platform which cause the software not to operate in material conformance to the Documentation, the Licensee shall submit to the Licensor a written report, via Licensor`s helpdesk portal linked to the site http://www.datatile.eu, describing the nature of such Errors in sufficient detail to permit the Licensor to reproduce and/or correct such Errors. Upon receipt of any such written reports, the Licensor agrees to use its best efforts to respond to the reported Errors at the latest within three Business days and prepare an update or patch program in a timely manner to correct such Errors as early as practicably possible.</p>
            <h2>3. Consideration</h2>
            <p><strong>3.1. Consideration for Grant of Rights.</strong> In consideration for the use of the DataTile Platform the Licensee shall pay the Licensor the non-refundable License Fees calculated based on the executed Order confirmation. </p>
            <p><strong>3.2. Extension of the License capacities</strong>. The Licensee shall use the DataTile Platform only within capacities described in the Order confirmation. Should the Licensee exceed prescribed capacities, the Licensee becomes due to pay additional License fee based on the rates to be specified in the Order confirmation.</p>
            <p><strong>3.3. Cost of services. </strong>The total cost of the additional services shall be set forth in each respective Licensee’s orders (if any will be placed and accepted by the Licensor). Any out-of-pocket expenses incurred in connection with the additional services for which the Licensor seeks reimbursement must be approved in advance by the Licensee and shall be reasonable, documented, and invoiced to the Licensee without mark-up.</p>
            <p><strong>3.4.Payments. </strong>All payments under this Agreement shall be made net of fees and charges by wire transfer to the Licensor`s bank account, identified by the Licensor herein. All payments must be made in the same currency as stated in the respective invoice. Any applicable taxes and levies, are not included in the aforesaid consideration. Licensee will make all payments of amounts due under this Agreement to Licensor free and clear of, and without reduction for, any withholding taxes, bank fees or charges. </p>
            <p>Unless otherwise stated in this Agreement, the Licensee undertakes to pay raised invoices within fifteen (15) days upon receipt of an invoice. Any payments by the Licensee that are not paid on or before the date such payments are due under this Agreement shall bear interest at a rate of 3% per annum.</p>
            <h2>4. Intellectual property and ownership of the DataTile Platform, Goodwill</h2>
            <p><strong>4.1. Ownership of the DataTile Platform. </strong>The Licensee acknowledges the ownership of the DataTile Platform in the Licensor, agrees that it will do nothing inconsistent with such ownership and that all use of the DataTile Platform by the Licensee shall inure to the benefit of the Licensor. The Licensee agrees that nothing in this Agreement shall give the Licensee any right, title or interest in the DataTile Platform other than the right to use the DataTile Platform in accordance with this Agreement and the Licensee agrees that it will not attack or impair the title of the Licensor to the DataTile Platform or attack the validity of this Agreement.</p>
            <p><strong>4.2. Goodwill. </strong>The Licensee recognizes the value of the goodwill associated with the DataTile Platform, and acknowledges that the DataTile Platform and all Intellectual Property Rights therein and goodwill pertaining thereto shall be solely owned by the Licensor.</p>
            <p><strong>4.3. Infringement proceedings.</strong> The Licensee shall notify the Licensor immediately of any information it obtains concerning any third party's infringement on the DataTile Platform right or other proprietary right of the Licensor with respect to the DataTile Platform and the Licensor shall notify the Licensee immediately of any information it obtains concerning any third party's infringement on the DataTile Platform right or other proprietary right of the Licensor with respect to the DataTile Platform that Licensor reasonably believes might affect the Licensee's rights under this Agreement. The Licensee shall, at its own expense, take such steps as it may consider necessary or desirable to protect its and/or the Licensor’s rights under this Agreement. </p>
            <h2>5. Warranty, Limitation of Liability</h2>
            <p>5.1. Licensee Warranties. The Licensee represents and warrants that:</p>
            <ol start="" role="list">
                <li>it is duly organized and validly existing under the laws of its domicile;</li>
                <li>it has the full right, power, and authority, including all necessary governmental authorizations and other approvals, to enter into and perform its obligations under this Agreement;</li>
                <li>the representative putting his or her signature on this Agreement or otherwise accepting this Agreement has been duly authorized by all necessary action;</li>
                <li>the representative using the DataTile Platform on behalf of the Licensee has been duly authorized by all necessary action;</li>
                <li>this Agreement, upon its execution by the legal representatives/authorized representatives of the Parties, shall come into full force and have binding forces upon the Parties;</li>
                <li>it will comply with all applicable laws, rules and regulations, including applicable privacy and data protection laws while using the DataTile Platform;</li>
                <li>each and every End User having access to the DataTile Platform will comply with conditions of this Agreement prescribed to the Licensee</li>
            </ol>
            <p><strong>5.2. Licensor Warranties.</strong>&nbsp;&nbsp;The Licensor represents and warrants that:</p>
            <ol start="" role="list">
                <li>it is duly organized and validly existing under the laws of its domicile;</li>
                <li>it has the full right, power, and authority, including all necessary governmental authorizations, licenses, and other approvals, to grant the rights and licenses described in this Agreement, free and clear of any and all claims, rights, and obligations of Third Parties;</li>
                <li>the representative putting his or her signature on this Agreement or otherwise accepting this Agreement has been duly authorized by all necessary action;</li>
                <li>it is the owner of the DataTile Platform and the owner of related Intellectual Property Rights, and that as of the Effective Date Licensor has not received any written notice from a third party that the DataTile Platform infringes or misappropriation, any patent, trademark, copyright, trade secret or other Intellectual Property Rights or proprietary rights;</li>
                <li>it will comply with all applicable laws, rules and regulations, including applicable privacy and data protection laws.</li>
                <li>the DataTile Platform does not and shall not, infringe the Intellectual Property Rights of any third party, and no consent of any third party is necessary for the performance of the parties' rights and obligations under this Agreement.</li>
                <li>this Agreement shall not conflict with any third-party agreements of the Licensor;</li>
                <li>The Licensee shall have no obligation to pay any third-party fees, royalties, or other payments for Licensee’ use of any third-party software in accordance with the terms of this Agreement;</li>
                <li>this Agreement, upon its execution by the legal representatives/authorized representatives of the Parties, shall come into full force and have binding forces upon the Parties.</li>
            </ol>
            <p><strong>5.3. Limitation of Liability.</strong> The Parties agree to indemnify the other Party from and against all claims and resulting liabilities, losses, damages, costs and expenses of any kind,including reasonable attorneys’ fees, initiated by or on behalf of third parties that are not affiliated with or related to the Indemnitee &nbsp;to the extent arising out of any breach or violation by the Indemnitor of its representations and warranties or other terms of this Agreement. The total and aggregate liability of a Party if any,arising out of or in any way related to this Agreement shall not exceed the License Fees actually paid by the Licensee for up to twelve (12) months prior to rise of a respective claim.</p>
            <p><strong>5.4. Disclaimer of Warranties. </strong>The Warranties set forth herein by the Licensor are limited warranties and are the only Warranties made by the Licensor. Except as may set forth herein the DataTile Platform is licensed “as is” without warranty of any kind. The Licensor does not warrant that the DataTile Platform is Error-free or its use will be uninterrupted. The Licensor expressly disclaims, and hereby expressly waives all other warranties, expressed or implied, including, without limitation, warranties of merchantability, warranties arising from course of dealing or course of performance.</p>
            <h2>6. Events of default and Remedies</h2>
            <p><strong>6.1. Events of Default.</strong> The Parties acknowledge and agree that the following shall constitute events of default (“Events of Default”) and that the occurrence of one (1) or more of such Events of Default shall constitute a material breach of this Agreement, which shall allow a Party, as applicable, to seek the rights and remedies set forth in this Subsection:</p>
            <ol start="" role="list">
                <li>Either Party's material breach of any warranty or other terms of this Agreement, provided that such breach, if curable, is not cured within fifteen (15) calendar days following receipt of written notice of such failure;</li>
                <li>Failure of a Party to perform any other material obligations under this Agreement, provided that such failure is not cured within fifteen (15) calendar days following receipt of written notice of such failure;</li>
                <li>Licensee’s failure to comply with conditions, set forth in Subsections 2.1., 2.2., 2.4., 2.5.</li>
            </ol>
            <p><strong>6.2. Rights and Remedies of the Licensor upon Default of the Licensee.</strong> Upon occurrence of an Event of Default by or with respect to the Licensee, the Licensor shall be entitled to any of the following remedies:</p>
            <ol start="" role="list">
                <li>terminate this Agreement subject to the term of Section 7; and/or</li>
                <li>seek to recover damages from Licensee; and/or</li>
                <li>exercise the right of self-help including stopping the technical support or disabling the DataTile Platform or blocking access to it without following the dispute resolution procedure and without creation of back-up files.</li>
            </ol>
            <p><strong>6.3. Rights and Remedies of the Licensee upon Default of the Licensor.</strong> Upon occurrence of an Event of Default by or with respect to the Licensor, the Licensee shall be entitled to any of the following remedies:</p>
            <ol start="" role="list">
                <li>terminate this Agreement subject to the term of Section 7; and/or</li>
                <li>seek to recover damages from the Licensor.</li>
            </ol>
            <h2>7. Term and Termination</h2>
            <p><strong>7.1. Term of Agreement.</strong> This Agreement has been duly executed by their authorized representatives as of the Effective Date and shall be effective simultaneously. This Agreement shall be valid for the Term of License as set forth in Section 2.3.</p>
            <p><strong>7.2. Termination for cause. </strong>This Agreement and all rights and licenses granted hereunder may be terminated:</p>
            <ol start="" role="list">
                <li>By either Party by delivery of a respective termination notice with immediate effect if the other Party becomes bankrupt, or is the subject of proceedings for liquidation or dissolution, or ceases to carry on business, subject to applicable mandatory law;</li>
                <li>By the Non-Affected Party if the consequences of an Event of Force Majeure (as defined below) excuse performance hereunder for a period in excess of thirty (30) days;</li>
                <li>By the non-breaching Party in the following circumstances: a Party is in material breach of the terms or conditions of this Agreement and such breach is not cured by such breaching Party within thirty (30) days after receipt of written notice of such breach from a non-breaching Party, then the non-breaching Party may at any time after expiry of such period, terminate this Agreement with immediate effect;</li>
                <li>By the Licensor if there is unauthorized use of Licensor's Intellectual Property Rights that is attributable to the Licensee's actions, actions of End Users and that is not attributable to the Licensor's actions. The Agreement is deemed to be terminated immediately upon delivery of a respective termination notice;</li>
                <li>By the Licensor by delivery of a respective termination notice with immediate effect &nbsp;if the Licensee fails to settle all fees and expenses, payable to the Licensor under this Agreement, overdue period is equal or more than thirty (30) calendar days.</li>
            </ol>
            <p><strong>7.3. </strong>The Parties may terminate this Agreement by mutual consent upon such terms as they may agree in writing.</p>
            <p><strong>7.4. Effect of termination. </strong>Sections/Subsections 1., 3., 4.1., 4.2., 5., 7.4.,8., 10., and any payment obligations that have accrued under this Agreement but have not been paid to the Licensor as of the date of termination, shall survive the termination of this Agreement according to their terms. Upon the termination of this Agreement pursuant to this Subsection 7.2., all amounts then due and unpaid by the Licensee hereunder, as well as all other amounts accrued but not yet payable by the Licensee at that time, shall become immediately due and payable to the Licensor. Upon termination of this Agreement, the Licensee agrees to (i) promptly delete all Licensee Data from the DataTile Platform; (ii) discontinue all use of the DataTile Platform. All rights in the DataTile Platform and the goodwill connected therewith shall remain the property of the Licensor upon termination. The Licensee retains all right,title and interest in and to all Licensee Data. If the Agreement is terminated,then all Licensee’s orders for additional services (if any) will be terminated accordingly.</p>
            <h2>8. Confidentiality</h2>
            <p><strong>8.1.</strong>"Confidential Information" shall mean all information relating to the Intellectual Property Rights and business practices of either Party including,without limitation: (i) the terms of this Agreement, Licensee Data, information relating to research and development, tools, techniques, methodologies,processes, lessons learned, models, know-how, algorithms, specifications,computer programs and software; and (ii) business plans, financial information,products, services, costs, sources of supply, strategic, advertising and marketing plans, customer lists, pricing methods, project proposals, personnel,and business relationships, including, without limitation, any information relating to the business or Intellectual Property Rights of either Party.</p>
            <p><strong>8.2.</strong>Neither Party receiving Confidential Information from the other Party shall (i)use Confidential Information received from the other Party under this Agreement for any purpose other than to fulfill its obligations under this Agreement;(ii) disclose such Confidential Information to any third party, except for those of its employees with a need to know the information in order to perform their obligations hereunder, and provided that they are made aware of and agree to be bound by the obligations of confidentiality contained herein or are bound by a similar written agreement containing terms regarding confidentiality that are at least as strict as those set forth herein. &nbsp;The receiving Party further agrees to use the same degree of care in safeguarding the Confidential Information as it uses for its own information, but in no event, less than a reasonable degree of care. &nbsp;The confidentiality obligations herein shall survive any expiration or termination of this Agreement. Each Party acknowledges that unauthorized disclosure of the other Party’s Confidential Information would cause irreparable harm to the other Party, and would entitle the other Party to seek injunctive relief upon disclosure or threatened disclosure, without a requirement to prove irreparable harm or the posting of a bond.</p>
            <p><strong>8.3.</strong> The obligation of confidentiality, however, shall not apply to information which:(i) is at the time of receipt or dissemination, or thereafter becomes,generally available to the public other than through a breach of this Agreement by the receiving Party; (ii) the receiving Party possessed at the time of receipt thereof from the disclosing Party, and was not acquired from the disclosing Party; (iii) is acquired or rightfully received without confidential limitation by the receiving Party from a third party; (iv) is independently developed by the receiving party without using or reference to the disclosing Party Confidential Information; or (v) is required to be disclosed pursuant to court order or applicable law, provided that the receiving party first gives the disclosing Party reasonable notice of such court order or law and an opportunity to oppose or attempt to limit such production. If the disclosing party is unable to obtain a protective order or other appropriate remedy with respect to such disclosure of Confidential Information, then the receiving party will disclose only that portion of the Confidential Information necessary to ensure compliance with such legal requirement.</p>
            <p><strong>8.4.</strong> The receiving Party will advise the disclosing Party immediately of any known or suspected breach or threat of breach of this Agreement, or of any unauthorized disclosure of Confidential Information, and will cooperate with the disclosing Party to regain possession of the Confidential Information and prevent its further unauthorized use or disclosure.</p>
            <p><strong>8.5.</strong> Upon termination of this Agreement or at the disclosing Party’s earlier written request, the receiving Party shall at disclosing Party’s option either: (i)return disclosing Party’s Confidential Information, in whatever form held by the receiving Party, or (ii) certify in a writing signed by a duly authorized officer or representative of the receiving Party that such Confidential Information, in whatever form held, has been destroyed. The Parties acknowledge, however, that a) Confidential Information provided in electronic format (e.g. e-mail) may be copied by the receiving Party as part of its normal back-up procedures and as such copies cannot be destroyed or returned to the disclosing Party each party agrees that it shall not access or utilize such copies following receipt of a request to return or destroy Confidential Information received from the disclosing Party other than for restore purposes and shall delete any Confidential Information following such restore and b) the receiving Party may retain one copy of the Confidential Information in its legal archive solely for the purpose of determining its obligations hereunder.</p>
            <p><strong>8.6.</strong> The Licensor understands and acknowledges that the Licensee may (i) manage, modify,maintain and update data and information related to any business activity of the Licensee or End Users for use with (or resulting from use of) the DataTile Platform, and (ii) generate, manage, modify, maintain and update such Licensee Data. Licensee Data shall be treated as Licensee Confidential Information, and the Licensee shall retain all right, title and interest in and to all Licensee Data. Notwithstanding the foregoing, the Licensee agrees that the Licensor will have access to Licensee Data comprising aggregated statistics relating to the usage of the DataTile Platform and (such as types and quantity of registered accounts, statistical information about the types of calculations being performed, for the purpose of calculation of License fees as well as for the purpose of improving the performance of the DataTile Platform). Such Licensee’s Data may be stored by the Licensor during and after expiration of the License Term for the audit, taxation, accounting and other related purposes.</p>
            <h2>9. Force Majeure</h2>
            <p><strong>9.1.</strong> Subject to the provisions of this Section, neither Party shall be liable to the other for any delay or failure to perform any of its obligations under this Agreement caused by a Force Majeure Event.</p>
            <p><strong>9.2.</strong> A Party seeking relief under this Section (“Affected Party”) must as soon as practicable (and in any event within three (3) Business Days after it became aware that a Force Majeure Event has caused or is likely to cause such delay or failure) notify the other Party in writing ("Non-Affected party") of the Force Majeure Event, the date of its occurrence and its likely duration.</p>
            <p><strong>9.3.</strong> The Affected Party shall notify the Non-Affected Party in writing if at any time it becomes aware of any further information relating to the Force Majeure Event.</p>
            <p><strong>9.4.</strong> If the Force Majeure Event specified in the notice continues for a period of more than 30 days the Non-Affected Party may, at any time after expiry of such period, terminate this Agreement with immediate effect.</p>
            <h2>10. Dispute Resolution</h2>
            <p><strong>10.1. Venue.&nbsp;</strong>All disputes, controversies or differences which may arise between the parties, out of or in relation to or in connection with this Agreement, or for the breach thereof, which have not been settled amicably in good faith by the Parties shall be finally settled by arbitration in Cyprus, Nicosia in accordance with the Cyprus arbitration rules. The award rendered by the arbitrator(s) shall be final and binding upon both parties concerned. The number of arbitrators shall be three. The seat, or legal place, of arbitration shall be Nicosia, Cyprus. The language to be used in the arbitral proceedings shall be English.</p>
            <p><strong>10.2. Governing Law.&nbsp;</strong>This Agreement shall be governed by the laws of Cyprus without regard to its conflict of law principles.</p>
            <h2>11. Miscellaneous</h2>
            <p><strong>11.1. Assignment and transfer.</strong> This Agreement will be binding upon and will inure to the benefit of the parties and their permitted successors and assigns, provided that either Party shall not assign or transfer this Agreement without the express prior written consent of the other Party.</p>
            <p><strong>11.2. Independent contractors. </strong>The<strong> </strong>Licensor is an independent contractor of, and not an employee, agent or authorized representative of, the Licensee. No agency, partnership, joint venture,employer-employee relationship, or other business combination between the Parties is intended or created by this Agreement. &nbsp;The Licensor will be responsible for payment and/or withholding of all income, social security, unemployment compensation,worker’s compensation, and other employment related taxes pertaining to the Licensor and its employees, and the Licensee will have no such responsibilities, nor will the Licensee be responsible for any health, life,disability or other benefits for the Licensor or its employees. &nbsp;</p>
            <p><strong>11.3. No Exclusivity.</strong> Each Party shall carry out its commitments under this Agreement in a manner that reflects favorably upon the good name and good will of the other Party. The Parties agree that the commitments under this Agreement are not exclusive and either Party may enter into similar agreements with third parties, including either Party's competitors.</p>
            <p><strong>11.4. Amendments.</strong> Except as otherwise provided herein, any amendment or modification to this Agreement shall be subject to the friendly negotiations between the Parties and shall not take effect unless the Parties have executed a written agreement with respect thereto.</p>
            <p><strong>11.5.</strong> In case any provision in this Agreement is held illegal, invalid or unenforceable,the legality, validity or enforceability of the remaining provisions herein shall not be affected or prejudiced in any aspect thereby.</p>
            <p><strong>11.6.</strong> This Agreement together with respective Order confirmation containsthe entire agreement and understanding among the parties hereto with respect tothe subject matter hereof, and supersedes all prior and contemporaneousagreements, understandings, inducements and conditions, express or implied,oral or written, of any nature whatsoever with respect to the subject matterhereof. The express terms hereof control and supersede any course ofperformance and/or usage of the trade inconsistent with any of the termshereof.</p>
            <p><strong>11.7. Notices. </strong>Except as otherwise provided herein, all notices and other communications under this Agreement shall be given in writing to the parties at the addresses appearing in this Agreement, or to such other address specified in writing to the notifying Party after the date of this Agreement and shall be deemed given on the date delivered in person, or on the next business day following delivery to a reputable overnight courier for next day delivery, or on the third business day following mailing by certified mail, return receipt requested. &nbsp;For this purpose, each day is a “business day” that is not a Saturday, Sunday or national holiday.</p>
            <p>‍</p>
        </div><a id="terms-SaaS" href="/document/627a6e2dabfbd0dabb4cd699_License%20Agreement%20Template%20(SaaS).pdf" target="_blank">Open PDF to download</a>
    </div>
</div>
<?php echo $__env->make("includes.footer", \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\OSPanel\domains\datatile\resources\views/footer_page/2.blade.php ENDPATH**/ ?>